# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 162d8d2f3e24314a6f8bcfae095f1d4a291641fbef13eda66e10aef44ea94fd62289fa6b40a31ccb625b155103ee6036787b06c761d50c6bb9f968a4f449dd8e

test:
  secret_key_base: 399710770e3da61f27b96c157918005bc92d3cc4dfa7e0ac003e03e5311960e3e350ec27dcf673264a6be721fdd30ac83a912c89b62b45d08d5bf95467347723

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
